# Generated by Django 4.2 on 2023-04-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('nick_name', models.CharField(max_length=20, verbose_name='Also known as')),
                ('occupation', models.CharField(max_length=200)),
                ('born', models.DateField(default='10-12-23', verbose_name='Born')),
                ('birth_palace', models.CharField(max_length=20, verbose_name='Birth_palace')),
                ('spouse', models.CharField(default='Savita', max_length=20)),
                ('children', models.PositiveIntegerField()),
                ('about', models.CharField(default='about the actor', max_length=2000, verbose_name='About The Actor')),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movies_name', models.CharField(max_length=20)),
                ('visual_type', models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX'), ('ICE 3D', 'ICE 3D'), ('4DX 3D', '4DX 3D')], max_length=10)),
                ('types', models.CharField(choices=[('Action', 'Action'), ('Romantic', 'Romantic'), ('Sad', 'Sad'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Funny', 'Funny'), ('Thriller', 'Thriller'), ('Comedy', 'Comedy'), ('Action/Drama', 'Action/Drama'), ('Action/Drama/Thriller', 'Action/Drama/Thriller'), ('Action/Comedy', 'Action/Comedy'), ('Horror/Romantic', 'Horror/Romantic'), (' Drama/funny', 'Drama/funny')], default='Action', max_length=50)),
                ('duration', models.DurationField(default='00h 00min 00sec', verbose_name='Duration')),
                ('ratings', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='0')),
                ('release_date', models.DateField(default='12/08/23', verbose_name='In cinemas')),
                ('about', models.CharField(default='about the movies', max_length=2000, verbose_name='About The Movie')),
            ],
        ),
    ]
